package com.example.myapplication.Model.Repositories.OpenWeatherAPI.Constants

class Lang {
    companion object {
        const val ARABIC = "ar"
        const val BULGARIAN = "bg"
        const val CATALAN = "ca"
        const val CZECH = "cz"
        const val GERMAN = "de"
        const val GREEK = "el"
        const val ENGLISH = "en"
        const val PERSIAN = "fa"
        const val FINNISH = "fi"
        const val FRENCH = "fr"
        const val GALICIAN = "gl"
        const val CROATIAN = "hr"
        const val HUNGARIAN = "hu"
        const val ITALIAN = "it"
        const val JAPANESE = "ja"
        const val KOREAN = "kr"
        const val LATVIAN = "la"
        const val LITHUANIAN = "lt"
        const val MACEDONIAN = "mk"
        const val DUTCH = "nl"
        const val POLISH = "pl"
        const val PORTUGUESE = "pt"
        const val ROMANIAN = "ro"
        const val RUSSIAN = "ru"
        const val SWEDISH = "se"
        const val SLOVAK = "sk"
        const val SLOVENIAN = "sl"
        const val SPANISH = "es"
        const val TURKISH = "tr"
        const val UKRAINIAN = "ua"
        const val VIETNAMESE = "vi"
        const val CHINESE_SIMPLIFIED = "zh_cn"
        const val CHINESE_TRADITIONAL = "zh_tw"
    }
}